### ISSUE TITLE
Extension shows "Please update FOE-Info" even after update

### ISSUE THREAD

**Issue by lango6** [FoE-Info/FoE-Info-Extension#2]
I went to the extension settings and clicked on the Update button.  The version shows 0.0.9, which agrees with what appears to be the latest version.  I've even tried uninstalling and reinstalling from the Chrome Web store.  I also updated to the latest version of Chrome, which surely cleared the cache, no?

Anyway, looking for guidance on getting this great extension working again.  Most of the info is not displaying.

**Comment by FoE-Info** [comment]
google have rejected the latest update, so I'm not able to provide an update via the web store.

I will add the latest version to download from github, or you can do so now from the discord server

**Comment by FoE-Info** [comment]
https://github.com/FoE-Info/chrome/releases/download/0.11/FoE-Info.zip

**Comment by HaoSs07** [comment]
Even after update to 0.11 error still happening. ( to update )

**Comment by FoE-Info** [comment]
still struggling with google not publishing the latest version. you can do a manual install of latest version

https://github.com/FoE-Info/chrome/releases/download/0.12/FoE-Info.zip

**Comment by kronikpillow** [comment]
this is solved
