### ISSUE TITLE
Blue Galaxy Helper breaks on game refresh

### ISSUE THREAD

**Issue by kronikpillow** [FoE-Info/FoE-Info-Extension#2]
The Blue Galaxy Helper gets stuck, and breaks, after collecting a few buildings and refreshing the game ...

once it breaks, it shows not collected buildings under the wrong building name

example: I Collected Druid Temple, refreshed the game, and it's still showing Druid Temple as not collected in the Helper

why is this important? you can accidentally close the Galaxy Helper, and then to re-trigger the panel you need to refresh the game

further details later once i investigate more on next collection

**Comment by BruceTheDominator** [comment]
ideally need screenshots to see what happens

**Comment by kronikpillow** [comment]
this was fixed in v.80
