### ISSUE TITLE
Guild Stats Notification Panel bug

### ISSUE THREAD

**Issue by kronikpillow** [FoE-Info/FoE-Info-Extension#27]
when using google sheets guild stats webhook ... and when visiting other players city, hitting post button, posts the notification shows up that it successfully posted to the spreadsheet, and then the panel, instead of being removed from the sidebar, sticks on the sidebar with no text in it ... looks flonky

successful post notification screenshot:
![pic-selected-220614-1158-53](https://user-images.githubusercontent.com/48420193/173551339-53832908-a3b5-436c-bc6d-9afc32d454e1.png)

after changing to a different player, the red panel stays, with no text in it:
![pic-selected-220614-1159-01](https://user-images.githubusercontent.com/48420193/173551341-f5d02626-4d8c-43c7-be01-6b90328082ce.png)
 
after the successful post notification goes away

**Comment by kronikpillow** [comment]
![pic-selected-220614-1205-34](https://user-images.githubusercontent.com/48420193/173552445-4adbf458-e59b-4432-8cff-ce94ed42c511.png)
![pic-selected-220614-1205-38](https://user-images.githubusercontent.com/48420193/173552449-213f8cfb-6692-4ac7-a3e4-8bba87cc5d10.png)

found this error in console log

**Comment by FoE-Info** [comment]
fixed in v77
