### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'defaultPrevented')

### ISSUE THREAD

**Issue by kronikpillow** [FoE-Info/FoE-Info-Extension#28]
![pic-selected-220614-1250-29](https://user-images.githubusercontent.com/48420193/173561033-ad7bed6c-01fd-4bb2-bfac-a1d3653cd9bd.png)

**Comment by kronikpillow** [comment]
not sure if this is related to this: [#27 ](https://github.com/FoE-Info/FoE-Info-Extension/issues/27#issuecomment-1154985403)

**Comment by FoE-Info** [comment]
fixed in v77
