### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by JhonnyBn** [FoE-Info/FoE-Info-Extension#3]
There is just obfuscated code here

**Comment by FoE-Info** [comment]
its minified, but its not obfuscated. you can easily pretty print it

the source project uses webpack, as you can see in the js files. it also includes premium features, which I'm not sharing here. the code I am sharing is the published version, which isnt allowed to be  obfuscated

**Comment by kronikpillow** [comment]
source code is now officially fully open source, you are free to download, review, modify, and make pull requests
