### ISSUE TITLE
Enhancement: Export Guild Member Stats to a csv file

### ISSUE THREAD

**Issue by odygrd** [FoE-Info/FoE-Info-Extension#4]
Hello, thank you for the plugin it is really useful. 
Unfortunately the source code is bundled so it is not easy to extent or maintain the plugin at the moment.

We are using the plugin to see and monitor the stats of our guild members. 
We would like that info to be easily exportable to a csv file.

This work the following way : 
1) You need to visit all guild members cities.
2) The city info of the guild members that is displayed on the FoeInfo window is also stored internally.
3) There is a new button that when pressed it will get the desired file. 

The csv file headers are
```
Name,Score,Era,Attack,Defense,Guild Goods
```

Below there is a reference implementation.
Please could you consider adding it to a future version ? It would be a nice feature to have

a) Store Player Stats : 

```js
class PlayerStats
{
  constructor(city_attack, city_defense, clan_goods, player_name, player_id, era, score)
  {
    this.city_attack = city_attack;
    this.city_defense = city_defense;
    this.clan_goods = clan_goods;
    this.player_name = player_name;
    this.player_era = era;
    this.player_id = player_id;
    this.player_score = score;
  }
}

var pstats = [];

// Needs to be called on player StartUpService on top
function fPrintSelfInfo(socialbarlist, player, visitCityAttack, visitCityDefense, clanGoods)
{
  // we figure out our score here from social bar list
  const found_player = socialbarlist.find(item =>
  {
    return item.player_id === player.player_id;
  });

  if (found_player)
  {
    fPrintInfo(true, found_player.era, found_player.name,  found_player.player_id, found_player.score,
      visitCityAttack, visitCityDefense, clanGoods )
  }
}

// Needs to be called on visit other player city on top
function fPrintInfo(is_guild_member, era, name, player_id, score, visitCityAttack, visitCityDefense, clanGoods)
{
  if (is_guild_member)
  {
    let found_player = pstats.find(item =>
    {
      return item.player_id === player_id;
    });

    if (found_player)
    {
      found_player.city_attack = visitCityAttack;
      found_player.city_defense = visitCityDefense;
      found_player.clan_goods = clanGoods;
      found_player.player_era = era;
      found_player.player_name = name;
      found_player.player_score = score;
    }
    else
    {
      pstats.push(new PlayerStats(visitCityAttack, visitCityDefense, clanGoods, name, player_id, era, score))
    }
  }
}
```

called on visit other player city on top as :
```js
//var player=msg.responseData.other_player;
fPrintInfo(player.is_guild_member, player.era, player.name, player.player_id, player.score, visitAttack, visitDefense, clanGoods);
```

called on startupservice as :
```js
//showStats&&checkVer()){
fPrintSelfInfo(msg.responseData.socialbar_list, msg.responseData.user_data, City.Attack, City.Defense, clanGoods)
```

b) Add a button to the gui
```js
var btn=document.createElement("button");btn.innerHTML = "GetGuildPlayerStats";btn.onclick = function () {fExportGuildStats();};js_content.appendChild(btn);
```

```js
function download(filename, text) {
  var element = document.createElement('a');
  element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
  element.setAttribute('download', filename);

  element.style.display = 'none';
  document.body.appendChild(element);

  element.click();

  document.body.removeChild(element);
}

function fExportGuildStats()
{
  let file_contents = 'Name,Score,Era,Attack,Defense,Guild Goods\n';
  let file_name = "player_stats_" + new Date().toISOString().slice(0, 10) + ".csv";
  pstats.forEach(item => {
    file_contents += item.player_name + "," + item.player_score + ","  + item.player_era + "," + item.city_attack + "," + item.city_defense + "," + item.clan_goods + "\n"})
  download(file_name,file_contents);
}
```

**Comment by FoE-Info** [comment]
thanks for the code. happy to add it to the tool

**Comment by odygrd** [comment]
Thank you a lot, that would be amazing :) Any estimate on the future version that can be added ? It seems like it is not in the newest 0.53 yet

**Comment by kronikpillow** [comment]
@odygrd I am not sure if this was ever implemented, due to the main dev's lack of time to work actively on the tool, but the source code is now fully open source, you are free to clone, modify, and make pull requests which will be reviewed by the main team ...

althou we took a different approach to this, instead of exporting to a CSV file, we decided to go with a solution where the Tool can push those stats directly to a spreadsheet on Google sheets, it's the "Google Sheet URL - Guild Info" option, in the tool settings

**Comment by kronikpillow** [comment]
Spreadsheet in question:
https://docs.google.com/spreadsheets/d/1VgfzxR2zBvtB0ZvNDu2UfS6bsPaAKQ17CY1NMUSZhcE/edit#gid=0

feel free to copy it ...
set the url to it, visit every player in your guild, and on his city info, hit the Guild button ... and it will record that players stats on it
